name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install npm dependencies for frontend
      run: npm install
      working-directory: ./frontend

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend

    # このステップは、frontendのビルドプロセスがbackend/staticにファイルを生成するため、省略可能です。
    # - name: Copy build to backend/static
    #   run: cp -r frontend/build/* backend/static/

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
      working-directory: ./backend

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./backend

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: test-sveltekit-fastapi
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend
